apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: replace-resources
  namespace: argocd
spec:
  destination:
    namespace: replace-resources
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sync-options/replace
    repoURL: "https://github.com/Gnauk841026/test2.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - Replace=true