apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Gnauk841026/test2.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----

    
