apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Gnauk841026/test.git 
  password: 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
  username: TestArgocd