apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-staging
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-staging
    server: "https://35.185.133.95"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true