apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: staging-aks-ams3-1
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "staging"
    provider: "aks"
type: Opaque
stringData:
  name: testremoteK8s
  server: https://35.185.133.95
  config: |
    {
      "bearerToken": "XXXX",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "XXXX"
      }
    }