apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: aks
        url: https://kubernetes.default.svc
      - cluster: gke
        url: https://35.185.133.95
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mabusaa/argocd-example-apps.git
        targetRevision: master
        path: guestbook
      destination:
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
         syncOptions:
          - CreateNamespace=true