apiVersion: v1
kind: Secret
metadata:
  name: local-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/secret-type: "cluster"
    custom-name: "aks-cluster"
    environment: "dev"
    provider: "local"
    non-production: "true"
type: Opaque
stringData:
  name: local-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
