apiVersion: v1
kind: Secret
metadata:
  name: testargoremote
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: dev
    provider: gke
type: Opaque
stringData:
  name: gke_terraform-429505_asia-east1_test-argo-remote
  server: https://35.185.133.95
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
